### ISSUE TITLE
Can't export mesh into armorpaint from blender

### ISSUE THREAD

**Issue by ninao-xyz** [PiloeGAO/Blender-ArmorPaintLiveLink#2]
Blender: 2.82a
ArmorPaint: git master branch 28614052222f3445a014453e792c05caad740333
OS: Solus Linux

Live link is configured according to the instructions in the README file.
When I click in the "Open into ArmorPaint" nothing appends.

There's the following error message in the blender info panel:

```
Traceback (most recent call last):
  File "/home/ninao/.config/blender/2.82/scripts/addons/armorpaint_livelink.py", line 340, in execute
    path_mode='AUTO')
  File "/usr/share/blender/2.82/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/usr/share/blender/2.82/scripts/addons/io_scene_obj/__init__.py", line 465, in execute
    return export_obj.save(context, **keywords)
  File "/usr/share/blender/2.82/scripts/addons/io_scene_obj/export_obj.py", line 787, in save
    EXPORT_PATH_MODE=path_mode,
  File "/usr/share/blender/2.82/scripts/addons/io_scene_obj/export_obj.py", line 729, in _write
    progress,
  File "/usr/share/blender/2.82/scripts/addons/io_scene_obj/export_obj.py", line 291, in write_file
    with open(filepath, "w", encoding="utf8", newline="\n") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ninao/Opt/armorpaint/data/tmp.obj'

location: /usr/share/blender/2.82/scripts/modules/bpy/ops.py:201



location: <unknown location>:-1


```

**Comment by ninao-xyz** [comment]
Ok, I figured out the issue, since I was building ArmorPaint from source, I had a executable shell script to start ArmorPaint, and apparently it needs to be inside the "cloned_repo_dir/build/krom"  for this add-on to work.

Shall I close this issue?

**Comment by joerno** [comment]
What does that mean, I have the same issue with windows 10 and no shell script. How to set the right path?
Thanks in advance

**Comment by PiloeGAO** [comment]
Hi @joerno,

When you build yourself ArmorPaint, you actually build two things:
- The ArmorPaint Source code from Haxe (in this directory: "armorpaint\build\krom")
- Krom for your OS:
Krom is the cross-platform "interpreter" for the compiled ArmorPaint source code.
By default, on start, Krom check in th current directory for "krom.js" and the data directory but the makefiles doesn't copy those files automaticly (and that why you need to parse "..\..\build\krom" at the Krom start).

To set the right path, you need to copy files from "armorpaint\build\krom" to the Krom build directory (aka: "armorpaint\Kromx\build\x64\Release").

Now, you can start ArmorPaint by executing "armorpaint\Kromx\build\x64\Release\Krom.exe".
After that, in the addon preferences, select "Krom.exe" in the "ArmorPaint Executable:" field.

For an optimum experience, please use the official release from the ArmorPaint website. (https://armorpaint.org/download.html)

**Comment by joerno** [comment]
Thanks for the fast reply. I copied the krom.exe to armorpaint\build\krom like in this video https://www.youtube.com/watch?v=y6h2KOP47ZY&t=582s and it starts like it should. 
Doing it your way works also and I get still the same error:

```
Traceback (most recent call last):
  File "C:\Users\myUser\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\armorpaint_livelink.py", line 340, in execute
    path_mode='AUTO')
  File "C:\Users\myUser\portable\media\blender-2.82a-windows64\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\myUser\portable\media\blender-2.82a-windows64\2.82\scripts\addons\io_scene_obj\__init__.py", line 465, in execute
    return export_obj.save(context, **keywords)
  File "C:\Users\myUser\portable\media\blender-2.82a-windows64\2.82\scripts\addons\io_scene_obj\export_obj.py", line 787, in save
    EXPORT_PATH_MODE=path_mode,
  File "C:\Users\myUser\portable\media\blender-2.82a-windows64\2.82\scripts\addons\io_scene_obj\export_obj.py", line 729, in _write
    progress,
  File "C:\Users\myUser\portable\media\blender-2.82a-windows64\2.82\scripts\addons\io_scene_obj\export_obj.py", line 291, in write_file
    with open(filepath, "w", encoding="utf8", newline="\n") as f:
FileNotFoundError: [Errno 2] No such file or directory: '//..\\..\\..\\development\\armorpaint\\Kromx\\build\\x64\\Release\\data\\tmp.obj'

location: C:\Users\myUser\portable\media\blender-2.82a-windows64\2.82\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1
```

I was founder of ArmorPaint till march, had to stop it... 
I'm using Windows 10 and Blendern 2.82a

**Comment by PiloeGAO** [comment]
I wasn't able to reproduce your bug but by doing some research I noted something.
Can you try using absolute path for ArmorPaint executable instead of relative in the addon preferences?

Thank you.

**Comment by joerno** [comment]
That worked for me, thanks a lot! And thanks for this plugin!
